spring.application.name=bill-payment-system
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Paystack
paystack.secret.key=${PAYSTACK_SECRET_KEY}
paystack.base.url=${PAYSTACK_BASE_URL:https://api.paystack.co}

# VTPass
vtpass.base.url=${VTPASS_BASE_URL:https://sandbox.vtpass.com/api}
vtpass.api.key=${VTPASS_API_KEY}
vtpass.secret.key=${VTPASS_SECRET_KEY}
vtpass.public.key=${VTPASS_PUBLIC_KEY}

# Email
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}

# App URL
app.frontend.url=${APP_FRONTEND_URL}
