# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/bill_payment_db
spring.datasource.username=postgres
spring.datasource.password=060nnexy#
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000 

# Paystack
paystack.secret.key=sk_test_974bbfbf7f11348035e83097e74ea674bb0e34f6
paystack.base.url=https://api.paystack.co

# VTPass
vtpass.base.url=https://sandbox.vtpass.com/api
vtpass.api.key=7cbd227bc2a80072efe28e8b678a4ff6
vtpass.secret.key=SK_884b0e064aed8de8105fd28afb8e691897e8d7a4339
vtpass.public.key=PK_77691f8e0d2b44fcd73f1aefa2e33f709230a031781